[WEB-3144]: Added SDK changes for flicker
CleverTap/clevertap-web-sdk pull request #243
Opened 2024-08-19 06:02 UTC by ThisIsRaghavGupta

Added changes to handle flicker management from the SDK

2024-09-17 07:33 UTC, kkyusuftk requested changes

2024-09-17 07:33 UTC, kkyusuftk commented on src/modules/visualBuilder/pageBuilder.js
> +        el.classList.add('wve-anti-flicker-show')
lets have these hardcoded classes in `builder_constants`

2024-09-18 06:44 UTC, KambleSonam approved these changes

2024-09-18 07:24 UTC, kkyusuftk approved these changes

2024-09-18 07:30 UTC, merged